services:
  db:
    image: mariadb:10.11
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=moodle
      - MARIADB_USER=moodle
      - MARIADB_PASSWORD=moodle
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    restart: unless-stopped

  moodle:
    image: moodlehq/moodle-php-apache:8.4
    ports:
      - "8082:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - moodle_data:/var/www/html
      - /home/reboot/Escritorio/edukamiUniverse-moodle/dist:/var/www/html/mod/edukami
      - moodledata_data:/var/www/moodledata
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MOODLE_DBTYPE=mariadb
      - MOODLE_DBHOST=db
      - MOODLE_DBNAME=moodle
      - MOODLE_DBUSER=moodle
      - MOODLE_DBPASS=moodle
      - MOODLE_URL=http://localhost:8082
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=Admin1234!Admin1234!
      - MOODLE_EMAIL=admin@example.com
      - MOODLE_SITE_FULLNAME=Moodle Local
      - MOODLE_SITE_SHORTNAME=MoodleLocal
    restart: unless-stopped

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:
